name: LRC 文件处理请求
description: 将目标 TTML 文件转换为 LRC 歌词文件
title: "[LRC] "
labels: ["lrc"]
body:
  - type: input
    id: url
    attributes:
      label: 文件 URL 地址
      description: |
        示例：
        https://raw.githubusercontent.com/username/repo/main/example.txt
    validations:
      required: true
  - type: dropdown
    id: extra
    attributes:
      label: 扩展内容（如果原歌词中有）
      description: |
        附加翻译/音译到 LRC 文件中
      options:
        - "无"
        - "翻译"
        - "音译"
      default: "无"
